### ISSUE TITLE
Can I get size of buffered image?

### ISSUE THREAD

**Issue by Masynchin** [elixir-mogrify/mogrify#105]
I want to render image blocks and then combine them into big one. To do this I need to calculate width and height of buffered images. I wrote [this code](https://github.com/Masynchin/ScheduleDrawer/blob/7d0ed28050365588c4870cb96e0ab5fc5549c319/lib/schedule_drawer.ex) with images manipulations that I looking for

**Comment by route** [comment]
Issues is not a good place to ask questions. Use discussions

**Comment by Masynchin** [comment]
> Issues is not a good place to ask questions. Use discussions

Couldn't find on mobile (I can see discussions section in React-Router, but can't in there)

**Comment by Masynchin** [comment]
> Couldn't find on mobile (I can see discussions section in React-Router, but can't in there)

Am I missing something?
![image](https://user-images.githubusercontent.com/47028153/145729087-d5a786a6-2a33-4880-86a3-50f33eeced81.png)
![image](https://user-images.githubusercontent.com/47028153/145729089-1bbdbda1-e604-4e96-a20c-67a42ce1f39e.png)

**Comment by route** [comment]
Weird, I created welcome one. Please check once again https://github.com/elixir-mogrify/mogrify/discussions
