### ISSUE TITLE
Svg to png font error

### ISSUE THREAD

**Issue by sonic182** [elixir-mogrify/mogrify#111]
Hi, do you know the safe way of converting SVG to PNG keeping the font style correct?

I have been trying it long time without success

I have something like this:

```elixir
    Mogrify.open(path_svg)
    |> Mogrify.format("png")
    |> Mogrify.resize("650x450")
    |> Mogrify.save(path: path_png)
```

for mi local docker works

for my ubuntu prod it uses I don't know which font...

**Comment by route** [comment]
Just install needed fonts on ubuntu. But first off it's not an issue, second it's not related to this repo as you are talking about imagemagick
